### ISSUE TITLE
Plugin not working on 1.15.2

### ISSUE THREAD

**Issue by eirikh1996** [dzjkb/EasyElevator#1]
Hello. I tried to run this plugin on 1.15.2. However, then trying to use an elevator, this shows up in console:
```
[ERROR] .... Could not pass event PlayerInteractEvent to EasyElevator v8.3

java.lang.ClassCastException: org.bukkit.material.MaterialData incompatible with org.bukkit.material.Sign

at dzjkb.EasyElevator.ElevatorCollection.getElevator(ElevatorCollection.java:91) ~[?:?]

at dzjkb.EasyElevator.EEPlayerListener.onPlayerInteract(EEPlayerListener.java:39) ~[?:?]

at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor18.execute(Unknown Source) ~[?:?]

at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-86]

at org.bukkit.plugin.EventExecutor$$Lambda$2980.000000001168F4F0.execute(Unknown Source) ~[?:?]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-86]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-86]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:561) ~[patched_1.15.2.jar:git-Paper-86]

at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:458) ~[patched_1.15.2.jar:git-Paper-86]

at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:448) ~[patched_1.15.2.jar:git-Paper-86]

at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1373) ~[patched_1.15.2.jar:git-Paper-86]

at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-86]

at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-86]

at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-86]

at net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$4199.0000000068080C40.run(Unknown Source) ~[?:?]

at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-86]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-86]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-86]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-86]

at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-86]

at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-86]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-86]

at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172) ~[patched_1.15.2.jar:git-Paper-86]

at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-86]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
```

**Comment by dzjkb** [comment]
Thanks for the logs - 1.15 support is planned and I've already identified roughly what needs to be done in that matter. I'll notify here and on discord when it's done.

**Comment by dzjkb** [comment]
A 1.15 version has been released, seems to be working fine - closing this issue.
